version: 2
jobs:
  build-darwin-brew:
    macos:
      xcode: '10.2.1'
    steps:
      - checkout
      - run:
          name: Prepare system
          command: |
            mkdir -p ~/.local/bin
            curl -Lk https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 -C ~/.local/bin
      - run:
          name: Install software
          command: |
            git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
            git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
            brew update
            brew install --cask adoptopenjdk/openjdk/adoptopenjdk8
            brew install gradle
      - run:
          name: Compute cache key
          command: |
            find . -name "*.cabal" -o -name "stack.yaml" -type f | sort | xargs cat > /tmp/stack-deps
      - restore_cache:
          keys:
            - inline-java-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
            - inline-java-stack-dependencies-{{ arch }}-
      - run:
          name: Build dependencies
          command: |
            ~/.local/bin/stack --no-terminal build -j2 --only-snapshot --prefetch --test --bench
      - save_cache:
          key: inline-java-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
          paths:
            - ~/.stack
      - run:
          name: Build and test
          command: |
            . set-java-home.sh
            # Make libjvm.dylib visible to the runtime linker
            ln -sf "$JAVA_HOME/jre/lib/server/libjvm.dylib" /usr/local/lib/libjvm.dylib
            ~/.local/bin/stack --no-terminal build -j2 \
                --test \
                --extra-lib-dirs=$JAVA_HOME/jre/lib/server/ \
                --extra-include-dirs=$JAVA_HOME/include/ \
                --extra-include-dirs=$JAVA_HOME/include/darwin/

  build-linux-linear:
    resource_class: xlarge
    docker:
        - image: tweag/linear-types:1.0.5
    working_directory: ~/inline-java
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update && apt-get install -y gradle openjdk-8-jdk
      - run:
          name: Compute cache key
          command: |
              (find . -name "*.cabal" -o -name "stack-linear.yaml" -type f) | sort | xargs cat > /tmp/stack-deps
      - restore_cache:
          keys:
            - inline-java-stack-linear-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
            - inline-java-stack-linear-dependencies-{{ arch }}-
      - run:
          name: Build dependencies
          command: |
            . env-linear.sh
            stack --no-terminal build --only-dependencies --prefetch --test -j4 jni jvm inline-java
      - save_cache:
          key: inline-java-stack-linear-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
          paths:
            - ~/.stack
            - .stack-work
      - run:
          name: Build project
          command: |
            . env-linear.sh
            stack --no-terminal build -j4 --pedantic --test --no-run-tests --no-run-benchmarks inline-java
      - run:
          name: Test
          command: |
            . env-linear.sh
            stack --no-terminal test jni jvm inline-java

workflows:
  version: 2
  build:
    jobs:
      - build-darwin-brew
