env:
  BAZEL_ARGS: --repository_cache=~/bazel-repository-cache --disk_cache=~/bazel-disk-cache
steps:
  - label: "Run tests"
    command: |
      nix-shell --pure --run "bazel test --test_output=all //... $BAZEL_ARGS"
    timeout: 30
  - label: "Install linear-types enabled GHC"
    command: |
      nix-shell shell-linear-types.nix --command ''
    timeout: 120
    key: "install-linear-ghc"
  - label: "Run tests (linear-types)"
    command: |
        nix-shell --pure --run "bazel test --test_output=all //... --config ghc_9_0_1 $BAZEL_ARGS" shell-linear-types.nix
    timeout: 60
    depends_on: "install-linear-ghc"
