steps:
  - label: "Run tests"
    command: |
      nix-shell --pure --run 'bazel test --test_output=all //...'
    timeout: 30
  - label: "Install linear-types enabled GHC"
    command: |
      nix-shell shell-linear-types.nix --command ''
    timeout: 120
    key: "install-linear-ghc"
  - label: "Run tests (linear-types)"
    command: |
        nix-shell --pure --run 'bazel test --test_output=all //jvm/tests/... //jni/tests/... //tests/... --config ghc_9_0_1' shell-linear-types.nix
    timeout: 60
    depends_on: "install-linear-ghc"
